# Site settings 配置站点
title: '路过音乐的博客'
url: 'https://www.lgyysblog.com' # your host
author: true
name: '路过音乐'
NickName: 'Gsong'
webtitle: '路过音乐的博客'
aboutyou: '个人Pages.Github博客，入行新手，请多关照！主要关注Python开发，地震学。'
portraits: '/assets/myavatar.jpg' # 照片

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  个人原创: '/myorigion.html'
  他人经典: '/otherclassical.html'
  娱乐主义: '/entertainment.html'
  关于博主: '/about.html'
  设置: '/configure.html'

# SNS
SNS: true
SNS-icon: #['facebook', 'weibo', 'QQ', 'github', 'Dribbble', 'twitter', 'instagram', 'weixin']
  mail: 'mailto: 532590979@qq.com'
  weixin: '/assets/images/IMG_0370.JPG' # your wechat image file path
  QQ: '/assets/images/IMG_0371.JPG' # your QQ image file path
  weibo: ''
  instagram: ''
  twitter: ''
  github: 'https://github.com/Gsonggit'
  Dribbble: ''
  facebook: ''
  Google: ''
  zhihu: ''

# 分页
paginate: 5
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'autumn'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zOTgxMy8xNjM0MA==' # 来必力评论uid
# Gitment评论 OAuth Application
Gitment: false
Gitment_owner: ''  # github用户名
Gitment_repo: ''  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: 'e72f1e75cf3b03f1c4aae39704fbb12b'

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
